/*******************************************************************************
* File Name: main.c
*
* Version: 1.0
*
* Description:
*  This is the source code for the project which demonstrates BLE data transfer
*  via GATT characteristic notification. 
*  This project sends data to be received by a Client device.
*
* Hardware Dependency:
*  CY8CKIT-042-BLE Bluetooth Low Energy (BLE) Pioneer Kit
*
********************************************************************************
* Copyright (2015), Cypress Semiconductor Corporation.
******************************************************************************
* This software is owned by Cypress Semiconductor Corporation (Cypress) and is
* protected by and subject to worldwide patent protection (United States and
* foreign), United States copyright laws and international treaty provisions.
* Cypress hereby grants to licensee a personal, non-exclusive, non-transferable
* license to copy, use, modify, create derivative works of, and compile the
* Cypress Source Code and derivative works for the sole purpose of creating
* custom software in support of licensee product to be used only in conjunction
* with a Cypress integrated circuit as specified in the applicable agreement.
* Any reproduction, modification, translation, compilation, or representation of
* this software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: CYPRESS MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, WITH
* REGARD TO THIS MATERIAL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* Cypress reserves the right to make changes without further notice to the
* materials described herein. Cypress does not assume any liability arising out
* of the application or use of any product or circuit described herein. Cypress
* does not authorize its products for use as critical components in life-support
* systems where a malfunction or failure may reasonably be expected to result in
* significant injury to the user. The inclusion of Cypress' product in a life-
* support systems application implies that the manufacturer assumes all risk of
* such use and in doing so indemnifies Cypress against all charges. Use may be
* limited by and subject to the applicable Cypress software license agreement.
*******************************************************************************/

/*******************************************************************************
* Included headers
*******************************************************************************/
#include <project.h>
#include <stdbool.h>
#include "common.h"


/*******************************************************************************
* Macros
*******************************************************************************/
#define MAX_MTU_SIZE                (512)
#define DEFAULT_MTU_SIZE            (23)


/*******************************************************************************
* Variables
*******************************************************************************/
bool charNotificationEnabled = false;
uint8 buffer[MAX_MTU_SIZE];
uint16 negotiatedMtu = DEFAULT_MTU_SIZE;


/*******************************************************************************
* Function Definitions
*******************************************************************************/


/*******************************************************************************
* Function Name: StackEventHandler()
********************************************************************************
* Summary:
* Event handler function for the BLE events processing.
*
* Parameters:
* uint32 eventCode: The event to be processed
* void * eventParam: Pointer to hold the additional information associated 
*                    with an event
*
* Return:
* None
*
* Theory:
* The function is responsible for handling the events generated by the stack.
* In addition to handling general events for BLE advertisement, connection, 
* and disconnection, this function updates the negotiated MTU size on the 
* MTU Exchange Request, and also enables/disables notifications for the custom
* characteristic.
*
* Side Effects:
* None
*
*******************************************************************************/
void StackEventHandler(uint32 eventCode, void * eventParam)
{
    CYBLE_GATTS_WRITE_REQ_PARAM_T writeParam;
    uint8 counter; 
    
    switch(eventCode)
    {
        /* Stack initialized; ready for advertisement */
        case CYBLE_EVT_STACK_ON:
            UART_UartPutString("\n\rAdvertising with Address: ");
            for(counter = 6; counter > 0; counter--)
            {
                UART_UartPutChar(HexToAscii(cyBle_deviceAddress.bdAddr[counter - 1], 1));
                UART_UartPutChar(HexToAscii(cyBle_deviceAddress.bdAddr[counter - 1], 0));
                UART_UartPutChar(' ');
            }
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;
        
        /* Advertisement timed out; Restart advertisement */
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            }
            break;

        case CYBLE_EVT_GAP_DEVICE_CONNECTED:
            UART_UartPutString("\n\rConnected. ");
            break;
            
        /* Device disconnected; restart advertisement */
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            charNotificationEnabled = false;
            UART_UartPutString("\n\n\rDisconnected. ");
            UART_UartPutString("\n\rAdvertising again. ");
            UART_UartPutString("Address: ");
            for(counter = 6; counter > 0; counter--)
            {
                UART_UartPutChar(HexToAscii(cyBle_deviceAddress.bdAddr[counter - 1], 1));
                UART_UartPutChar(HexToAscii(cyBle_deviceAddress.bdAddr[counter - 1], 0));
                UART_UartPutChar(' ');
            }
            negotiatedMtu = DEFAULT_MTU_SIZE;
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            break;

        /* GATT MTU exchange request - Update the negotiated MTU value */
        case CYBLE_EVT_GATTS_XCNHG_MTU_REQ:
            negotiatedMtu = (((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu < CYBLE_GATT_MTU) ?
                            ((CYBLE_GATT_XCHG_MTU_PARAM_T *)eventParam)->mtu : CYBLE_GATT_MTU;
            break;
            
        /* Check if the Client Characteristic Configuration Descriptor is
         * written to. Notification is enabled or disabled accordingly.
         */
        case CYBLE_EVT_GATTS_WRITE_REQ:
            writeParam = *(CYBLE_GATTS_WRITE_REQ_PARAM_T *)eventParam;
            if(writeParam.handleValPair.attrHandle == 
               CYBLE_CUSTOM_SERVICE_CUSTOM_CHARACTERISTIC_CLIENT_CHARACTERISTIC_CONFIGURATION_DESC_HANDLE)
            {
                charNotificationEnabled = writeParam.handleValPair.value.val[0];
            }
            CyBle_GattsWriteRsp(cyBle_connHandle);
            break;
            
        default:
            break;
    }
}


/*******************************************************************************
* Function Name: SendNotification()
********************************************************************************
* Summary:
* This function creates a notification packet and sends it.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* The function creates a notification packet for the custom characteristic and 
* sends it over BLE. The amount of data sent for the characteristic is equal 
* to (negotiated MTU size - 3) bytes.
*
* Side Effects:
* None
*
*******************************************************************************/
void SendNotification(void)
{
    /* Create a new notification packet */
    CYBLE_GATTS_HANDLE_VALUE_NTF_T notificationPacket;
    
    /* Update Notification packet with the data.
     * Maximum data which can be sent is equal to (Negotiated MTU - 3) bytes.
     */
    notificationPacket.attrHandle = CYBLE_CUSTOM_SERVICE_CUSTOM_CHARACTERISTIC_CHAR_HANDLE;
    notificationPacket.value.val = buffer;
    notificationPacket.value.len = negotiatedMtu - 3;
    
    /* Report data to BLE component */
    CyBle_GattsNotification(cyBle_connHandle, &notificationPacket);
}


/*******************************************************************************
* Function Name: main()
********************************************************************************
* Summary:
* The top-level application function for the project.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* This is the main function for the application. It does the following -
* 1. Initializes the BLE component
* 2. Initializes a buffer from which data is sent out over BLE
* 3. Sends characteristic notification packets over BLE
*
* Side Effects:
* None
*
*******************************************************************************/
int main()
{
    uint32 counter = 0; 

    /* Enable global interrupts for BLE */
    CyGlobalIntEnable; 
    
    /* Initialize components */
    CyBle_Start(StackEventHandler);
    UART_Start();

    /* Clear screen and put a welcome message */
    UART_UartPutChar(12);
    UART_UartPutString("========= BLE GATT Throughput Measurement - Server side =========\n\n\r");
    
    /* Initialize entire buffer; the amount of data send will 
     * depend on the peer device's MTU */
    for(counter = 0; counter < MAX_MTU_SIZE; counter++)
    {
        buffer[counter] = counter;
    }
    
    for(;;)
    {
        /* Send data via characteristic notifications */
        if(charNotificationEnabled == true)
        {
            /* Send new data only when the previous data has gone out, 
             * which is indicated by Stack being Free.
             */
            if(CyBle_GattGetBusStatus() == CYBLE_STACK_STATE_FREE)
            {
                SendNotification();
            }
        }

        /* Mandatory to process BLE events generated by stack */
        CyBle_ProcessEvents();
    }
}

/* [] END OF FILE */
