/*******************************************************************************
* File Name: main.c
*
* Version: 1.0
*
* Description:
*  This is the source code for the BLE connection parameters update request demo
*  project.
*
* Hardware Dependency:
*  CY8CKIT-042 BLE
*
********************************************************************************
* Copyright (2015), Cypress Semiconductor Corporation.
******************************************************************************
* This software is owned by Cypress Semiconductor Corporation (Cypress) and is
* protected by and subject to worldwide patent protection (United States and
* foreign), United States copyright laws and international treaty provisions.
* Cypress hereby grants to licensee a personal, non-exclusive, non-transferable
* license to copy, use, modify, create derivative works of, and compile the
* Cypress Source Code and derivative works for the sole purpose of creating
* custom software in support of licensee product to be used only in conjunction
* with a Cypress integrated circuit as specified in the applicable agreement.
* Any reproduction, modification, translation, compilation, or representation of
* this software except as specified above is prohibited without the express
* written permission of Cypress.
*
* Disclaimer: CYPRESS MAKES NO WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, WITH
* REGARD TO THIS MATERIAL, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
* WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.
* Cypress reserves the right to make changes without further notice to the
* materials described herein. Cypress does not assume any liability arising out
* of the application or use of any product or circuit described herein. Cypress
* does not authorize its products for use as critical components in life-support
* systems where a malfunction or failure may reasonably be expected to result in
* significant injury to the user. The inclusion of Cypress' product in a life-
* support systems application implies that the manufacturer assumes all risk of
* such use and in doing so indemnifies Cypress against all charges. Use may be
* limited by and subject to the applicable Cypress software license agreement.
*******************************************************************************/

/*****************************************************************************
* Included headers
*****************************************************************************/
#include <project.h>


/*****************************************************************************
* Connection Parameters structure
*****************************************************************************/
CYBLE_GAP_CONN_UPDATE_PARAM_T connectionParameters = 
{
    400,                /* Minimum connection interval - 400 x 1.25 = 500 ms */
    400,                /* Maximum connection interval - 400 x 1.25 = 500 ms */
    1,                  /* Slave latency - 1 */
    500                 /* Supervision timeout - 500 x 10 = 5000 ms */
};


/*****************************************************************************
* Function Definitions
*****************************************************************************/


/*****************************************************************************
* Function Name: StackEventHandler()
******************************************************************************
* Summary:
* Event handler for the BLE events processing.
*
* Parameters:
* uint32 eventCode: The event to be processed
* void * eventParam: Pointer to hold the additional information associated 
*                    with an event
*
* Return:
* None
*
* Theory:
* The function is responsible for handling the events generated by the stack.
* In addition to handling general events for BLE advertisement, connection, 
* and disconnection, this function handles the BLE connection parameter
* update response event.
*
* Side Effects:
* None
*
*****************************************************************************/
void StackEventHandler(uint32 eventCode, void * eventParam)
{
    static uint8 ledToggle = 0;
    
    switch(eventCode)
    {
        /* Stack is initialized. Start advertisement. */
        case CYBLE_EVT_STACK_ON:
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);

            /* Turn OFF all LEDs */
            Led_Red_Write(1);
            Led_Green_Write(1);
            Led_Blue_Write(1);
            break;
            
        /* Advertisement timed out. Restart advertisement. */
        case CYBLE_EVT_GAPP_ADVERTISEMENT_START_STOP:
            if(CyBle_GetState() == CYBLE_STATE_DISCONNECTED)
            {
                CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);
            }
            break;
            
        /* Device is disconnected. Restart advertisement. */
        case CYBLE_EVT_GAP_DEVICE_DISCONNECTED:
            CyBle_GappStartAdvertisement(CYBLE_ADVERTISING_FAST);

            /* Turn OFF all LEDs */
            Led_Red_Write(1);
            Led_Green_Write(1);
            Led_Blue_Write(1);
            break;

            
        /* This event is generated when a response is received for the 
         * connection parameter update request.
         * If the request is accepted by the Master, one of the Green and Blue
         * LEDs is turned ON. Each time the SW2 switch is pressed, a new request
         * is sent to the Master, and upon every acceptance, the LED toggles 
         * between Green and Blue color.
         * If the request is rejected by the Master, the Green and Blue LEDs are
         * turned OFF and the Red LED is turned ON.
         */
        case CYBLE_EVT_L2CAP_CONN_PARAM_UPDATE_RSP:
            if(*(uint8 *)eventParam == 0x00)
            {
                /* Connection parameter update request accepted by Master */

                /* Turn OFF Red LED */
                Led_Red_Write(1);
                
                /* Toggle between Green and Blue LED */
                if(ledToggle == 0)
                {
                    ledToggle = 1;
                    Led_Blue_Write(1);
                    Led_Green_Write(0);
                }
                else if(ledToggle == 1)
                {
                    ledToggle = 0;
                    Led_Green_Write(1);
                    Led_Blue_Write(0);
                }
            }
            else if(*(uint8 *)eventParam == 0x01)
            {
                /* Connection parameter update request rejected by Master */
                
                /* Turn ON Red LED; Turn OFF Green and Blue LEDs */
                Led_Green_Write(1);
                Led_Blue_Write(1);
                Led_Red_Write(0);
            }
            break;
            
        default:
            break;
    }
}


/*****************************************************************************
* Function Name: UserSwitchIsr()
******************************************************************************
* Summary:
* ISR for the user switch GPIO interrupt.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* This ISR is triggered everytime the SW2 switch is pressed on the
* CY8CKIT-042 BLE Pioneer Kit. If the device is connected to a peer BLE device,
* a connection parameter update request is sent to the peer device. The 
* parameters are defined in the structure 'connectionParameters' defined above 
* in this file.
*
* Side Effects:
* None
*
*****************************************************************************/
CY_ISR(UserSwitchIsr)
{
    /* On every switch press, if the device is connected, send a BLE
     * connection parameter update request. 
     */
    if(CyBle_GetState() == CYBLE_STATE_CONNECTED)
    {
        /* The parameters to the API are  - 
         * 1. Peer device's BD handle
         * 2. Pointer to 'connectionParameters' structure defined in this file
         */
        CyBle_L2capLeConnectionParamUpdateRequest(cyBle_connHandle.bdHandle, &connectionParameters);
    }
    
    /* Clear pending interrupt */
    SW2_ClearInterrupt();
}


/*****************************************************************************
* Function Name: main()
******************************************************************************
* Summary:
* Main function for the application.
*
* Parameters:
* None
*
* Return:
* None
*
* Theory:
* This function initializes the BLE component and the SW2 switch interrupt, 
* and then processes the BLE events routinely, while also implementing low
* power in the system.
*
* Side Effects:
* None
*
*****************************************************************************/
int main()
{
    CYBLE_LP_MODE_T bleState;
    uint8 interruptStatus;

    /* Enable global interrupts */
    CyGlobalIntEnable; 
    
    /* Start BLE component */
    CyBle_Start(StackEventHandler);
    
    /* Configure User switch interrupt */
    SW2_Interrupt_StartEx(UserSwitchIsr);
    
    for(;;)
    {
        /* Routinely called every connection interval to process
         * pending BLE events. */
        CyBle_ProcessEvents();
        
        
        /* Low Power Implementation with BLE */
        bleState = CyBle_EnterLPM(CYBLE_BLESS_DEEPSLEEP);
        interruptStatus = CyEnterCriticalSection();
        if(bleState == CYBLE_BLESS_DEEPSLEEP)
        {
            if((CyBle_GetBleSsState() == CYBLE_BLESS_STATE_ECO_ON) || 
               (CyBle_GetBleSsState() == CYBLE_BLESS_STATE_DEEPSLEEP))
            {
                CySysPmDeepSleep();
            }
        }
        else
        {
            if(CyBle_GetBleSsState() != CYBLE_BLESS_STATE_EVENT_CLOSE)
            {
                CySysPmSleep();
            }
        }
        CyExitCriticalSection(interruptStatus);
        
    }
}

/* [] END OF FILE */
